# Generated by Django 2.0.9 on 2020-06-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200612_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userinfo'),
        ),
    ]
