# Generated by Django 2.0.9 on 2020-06-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userinfo'),
        ),
    ]
