# Generated by Django 2.0.9 on 2020-06-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comments_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
