# Generated by Django 2.0.9 on 2020-06-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comments_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='feelings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='feelingfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feelings'),
        ),
    ]
