# Generated by Django 2.0.9 on 2020-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200615_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feelingfile',
        ),
        migrations.AddField(
            model_name='post',
            name='feeling',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='feelings',
        ),
    ]
