# Generated by Django 2.0.9 on 2020-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200615_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='cover_pictures/'),
        ),
    ]
