# Generated by Django 2.0.9 on 2020-06-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
